
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Label lblTitulo;
	
	private global::Gtk.Entry txtInput;
	
	private global::Gtk.Button btnCliqueAqui;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.lblTitulo = new global::Gtk.Label ();
		this.lblTitulo.Name = "lblTitulo";
		this.lblTitulo.LabelProp = global::Mono.Unix.Catalog.GetString ("Um texto qualquer");
		this.vbox1.Add (this.lblTitulo);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblTitulo]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.txtInput = new global::Gtk.Entry ();
		this.txtInput.CanFocus = true;
		this.txtInput.Name = "txtInput";
		this.txtInput.IsEditable = true;
		this.txtInput.InvisibleChar = '•';
		this.vbox1.Add (this.txtInput);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.txtInput]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.btnCliqueAqui = new global::Gtk.Button ();
		this.btnCliqueAqui.CanFocus = true;
		this.btnCliqueAqui.Name = "btnCliqueAqui";
		this.btnCliqueAqui.UseUnderline = true;
		this.btnCliqueAqui.Label = global::Mono.Unix.Catalog.GetString ("Clique Aqui");
		this.vbox1.Add (this.btnCliqueAqui);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnCliqueAqui]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnCliqueAqui.Clicked += new global::System.EventHandler (this.clicou);
	}
}
